### ISSUE TITLE
EventDB deprecation

### ISSUE THREAD

**Issue by taalas** [Icinga/icingaweb2-module-eventdb#29]
I am fairly new to the Icinga2 framework and would like to add SNMP trap aggregation and service checks. Reading up on EventDB it seems that it is flagged as deprecated now (in the Netways Git repo). Is it still feasible to use though? Is there any other way to use this module?

Thanks!

**Comment by lazyfrosch** [comment]
EventDB is deprecated, but there are still some users. The module has been open sourced so everyone can use it.

Please don't expect community support for it :wink:
