### ISSUE TITLE
Fuzzy link to hostnames

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2-module-eventdb#5]
It would be great if the Host Link would not trigger an exact search. A Fuzzy search would help to prevent errors and optimize the user experience

![001_host_error](https://cloud.githubusercontent.com/assets/4162281/23019112/0788ce4c-f441-11e6-865f-599281b167bb.PNG)
![002_host_error](https://cloud.githubusercontent.com/assets/4162281/23019110/07875c7e-f441-11e6-8767-a0f50f4c3142.PNG)
![003_host_error_search](https://cloud.githubusercontent.com/assets/4162281/23019111/07885bba-f441-11e6-8d71-4c2cb7d1c13d.PNG)

**Comment by Al2Klimov** [comment]
IMO @lippserd should decide whether to "fix" this the way you suggest. (I'm afraid he will just say "forget it".)

**Comment by Al2Klimov** [comment]
May be we could query by custom variables instead of the host name. But I don't want to decide that (right now).

**Comment by SimonHoenscheid** [comment]
@JensKrone FYI

**Comment by lazyfrosch** [comment]
This is largely because the monitoring module is using case-sensitive match on calling the hostname.

It would make sense to link via an helper function inside this module here.

    eventdb/host/goto?name=lowercase

This should be part of a functionality to link back from host or service...
