### ISSUE TITLE
Popup Tool Tips for Action Buttons in Interface missing 

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2-module-eventdb#7]
The Action Bar above the Events is missing tool tips for explaining the functions.

**Comment by Al2Klimov** [comment]
Only the father of understanding and @lippserd know how to explain these ;)

**Comment by lazyfrosch** [comment]
I'll add titles to severity and ack.

**Comment by lazyfrosch** [comment]
See cc608c4dedb067ec810ec31b1fda31de817e6d07 in PR #11
