### ISSUE TITLE
Acknowledgement only available in multi selection

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2-module-eventdb#8]
Pressing the ACK Button does not Change something. ACK is not set to 1 in DB or set back to 0 if removed. Please Fix.

**Comment by Al2Klimov** [comment]
IMO it's just a filter, but feel free to ask @lippserd ...

**Comment by JensKrone** [comment]
How is it planned to set an acknowledge?

**Comment by tfvbhz** [comment]
I had the same Problem.
If you select serveral entries you can ack them.

**Comment by JensKrone** [comment]
Thanks
